#############################################################################
# Makefile for building: imageviewer-qt5.app/Contents/MacOS/imageviewer-qt5
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  imageviewer-qt5.pro
# Template: app
# Command: /usr/local/Cellar/qt/5.13.1/bin/qmake -o Makefile imageviewer-qt5.pro -spec macx-clang CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.13.1/lib
QMAKE         = /usr/local/Cellar/qt/5.13.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Cellar/qt/5.13.1/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Cellar/qt/5.13.1/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = imageviewer-qt51.0.0
DISTDIR = /Users/ferdiarmagan/Desktop/Computergrafik\ 2/Uebung_1/.tmp/imageviewer-qt51.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.13.1/lib -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = imageviewer-qt5.cpp \
		imageviewer-main-qt5.cpp moc_imageviewer-qt5.cpp
OBJECTS       = imageviewer-qt5.o \
		imageviewer-main-qt5.o \
		moc_imageviewer-qt5.o
DIST          = /usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/lex.prf \
		imageviewer-qt5.pro imageviewer-qt5.h imageviewer-qt5.cpp \
		imageviewer-main-qt5.cpp
QMAKE_TARGET  = imageviewer-qt5
DESTDIR       = 
TARGET        = imageviewer-qt5.app/Contents/MacOS/imageviewer-qt5

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/ferdiarmagan/Desktop/Computergrafik 2/Uebung_1/imageviewer-qt5.pro


include /usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

imageviewer-qt5.app/Contents/MacOS/imageviewer-qt5:  $(OBJECTS)  
	@test -d imageviewer-qt5.app/Contents/MacOS/ || mkdir -p imageviewer-qt5.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: imageviewer-qt5.pro /usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/lex.prf \
		imageviewer-qt5.pro \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile imageviewer-qt5.pro -spec macx-clang CONFIG+=x86_64
/usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/lex.prf:
imageviewer-qt5.pro:
/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/QtPrintSupport.prl:
/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile imageviewer-qt5.pro -spec macx-clang CONFIG+=x86_64

qmake_all: FORCE

imageviewer-qt5.app/Contents/PkgInfo: 
	@test -d imageviewer-qt5.app/Contents || mkdir -p imageviewer-qt5.app/Contents
	@$(DEL_FILE) imageviewer-qt5.app/Contents/PkgInfo
	@echo "APPL????" > imageviewer-qt5.app/Contents/PkgInfo
imageviewer-qt5.app/Contents/Resources/empty.lproj: 
	@test -d imageviewer-qt5.app/Contents/Resources || mkdir -p imageviewer-qt5.app/Contents/Resources
	@touch imageviewer-qt5.app/Contents/Resources/empty.lproj
	
imageviewer-qt5.app/Contents/Info.plist: 
	@test -d imageviewer-qt5.app/Contents || mkdir -p imageviewer-qt5.app/Contents
	@$(DEL_FILE) imageviewer-qt5.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.armaganindustries.imageviewer-qt5,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.armaganindustries.imageviewer-qt5,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,imageviewer-qt5,g" -e "s,@LIBRARY@,imageviewer-qt5,g" -e "s,\$${EXECUTABLE_NAME},imageviewer-qt5,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/Info.plist.app >imageviewer-qt5.app/Contents/Info.plist

all: Makefile \
		imageviewer-qt5.app/Contents/PkgInfo \
		imageviewer-qt5.app/Contents/Resources/empty.lproj \
		imageviewer-qt5.app/Contents/Info.plist imageviewer-qt5.app/Contents/MacOS/imageviewer-qt5

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.13.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents imageviewer-qt5.h $(DISTDIR)/
	$(COPY_FILE) --parents imageviewer-qt5.cpp imageviewer-main-qt5.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r imageviewer-qt5.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_) -spec macx-clang CONFIG+=x86_64

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.13.1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.13.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_imageviewer-qt5.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_imageviewer-qt5.cpp
moc_imageviewer-qt5.cpp: imageviewer-qt5.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers/QPrinter \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers/qprinter.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.13.1/bin/moc
	/usr/local/Cellar/qt/5.13.1/bin/moc $(DEFINES) --include '/Users/ferdiarmagan/Desktop/Computergrafik 2/Uebung_1/moc_predefs.h' -I/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang -I'/Users/ferdiarmagan/Desktop/Computergrafik 2/Uebung_1' -I/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/usr/local/Cellar/qt/5.13.1/lib imageviewer-qt5.h -o moc_imageviewer-qt5.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

imageviewer-qt5.o: imageviewer-qt5.cpp /usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QtWidgets \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qabstractslider.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qactiongroup.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcolordialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcolormap.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcolumnview.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qcompleter.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdial.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdirmodel.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdockwidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdrawutil.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qerrormessage.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qfocusframe.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qfontdialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qformlayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgesture.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qheaderview.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qlistview.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmdiarea.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qprogressbar.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qproxystyle.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qrubberband.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qscroller.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qshortcut.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qsizegrip.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qslider.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qspinbox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qsplitter.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstyle.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstylefactory.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstyleoption.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstylepainter.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtabbar.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtableview.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtabwidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtoolbox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtooltip.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtreeview.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtreewidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qundogroup.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qundostack.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qundoview.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qwizard.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers/QPrintDialog \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers/qprintdialog.h \
		imageviewer-qt5.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers/QPrinter \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers/qprinter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageviewer-qt5.o imageviewer-qt5.cpp

imageviewer-main-qt5.o: imageviewer-main-qt5.cpp /usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Headers/QCommandLineParser \
		/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Headers/qcommandlineparser.h \
		imageviewer-qt5.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers/QPrinter \
		/usr/local/Cellar/qt/5.13.1/lib/QtPrintSupport.framework/Headers/qprinter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageviewer-main-qt5.o imageviewer-main-qt5.cpp

moc_imageviewer-qt5.o: moc_imageviewer-qt5.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageviewer-qt5.o moc_imageviewer-qt5.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/Cellar/qt/5.13.1/examples/widgets/widgets/imageviewer || mkdir -p $(INSTALL_ROOT)/usr/local/Cellar/qt/5.13.1/examples/widgets/widgets/imageviewer
	$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Cellar/qt/5.13.1/examples/widgets/widgets/imageviewer/imageviewer-qt5.app
	
	-$(QINSTALL) imageviewer-qt5.app $(INSTALL_ROOT)/usr/local/Cellar/qt/5.13.1/examples/widgets/widgets/imageviewer/imageviewer-qt5.app
	-$(STRIP) $(INSTALL_ROOT)/usr/local/Cellar/qt/5.13.1/examples/widgets/widgets/imageviewer/imageviewer-qt5.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Cellar/qt/5.13.1/examples/widgets/widgets/imageviewer/imageviewer-qt5.app
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/Cellar/qt/5.13.1/examples/widgets/widgets/imageviewer/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

